### ISSUE TITLE
Connect menus in the experiments with Kitsune

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-experiments#9]
We need to connect dynamically/statically the menu entries with existing categories/articles in Kitsune.

**Comment by akatsoulas** [comment]
PR #18 is for the first experiment (index.hmlt).

**Comment by akatsoulas** [comment]
We need to clarify what's the exact list of links for the menu in the `insecure password warning` article. cc @madasan

**Comment by madasan** [comment]
@jonisavage can you help here?

**Comment by jonichan** [comment]
@akatsoulas We should get rid of the links after "Protect your Privacy" since it's supposed to reflect the breadcrumb for the article. So "Updates and Install" shouldn't be there at all.

"Cookies and Cache" should be in "Protect your privacy" and that should be the only thing in there because that's the only subtopic in that category in the structure. Cookies and Cache should link to: https://support.mozilla.org/products/firefox/protect-your-privacy/cookies

**Comment by akatsoulas** [comment]
Relevant pr #28

**Comment by akatsoulas** [comment]
this is merged.
